### ISSUE TITLE
Patching system watchers for the `ENOSPC` error when running expo/expo-github-action@v6

### ISSUE THREAD

**Issue by javascripter** [expo/expo-github-action#133] opened 2022-01-06 04:20 UTC
### Description of the bug
expo-github-action fails with `Error: Error: The process '/usr/local/bin/yarn' failed with exit code null` when running on GitHub Actions. Updating node to 16.x did not solve the issue.
https://github.com/expo/expo-github-action/issues/132#issuecomment-992245294

Also, I tried `patch-watchers: false` but it resulted in an error as well. With `patch-watchers: false`, the below error was thrown with no detailed info.
```
Error: Error: The process '/usr/local/bin/yarn' failed with exit code null
```

### To Reproduce
Running the below workflow on GitHub Actions.
```
name: EAS build
on:
  workflow_dispatch:

jobs:
  build:
    name: Create new build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v6
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
```

#### Expected behavior
Runs without errors.
#### Actual behavior
The action fails with the following error:
```
Run expo/expo-github-action@v6
  with:
    expo-version: latest
    eas-version: latest
    token: ***
    expo-cache: false
    eas-cache: false
    packager: yarn
    patch-watchers: true
Installing expo-cli (5.0.3) with yarn
Installing eas-cli (0.43.0) with yarn
Checking current authenticated account
Patching system watchers for the `ENOSPC` error
  Patching system watchers for the `ENOSPC` error...
  /usr/bin/sudo sysctl fs.inotify.max_user_instances=524288
  Error: Error: The process '/usr/local/bin/yarn' failed with exit code null
  fs.inotify.max_user_instances = 524288
  /usr/bin/sudo sysctl fs.inotify.max_user_watches=524288
  fs.inotify.max_user_watches = 524288
  /usr/bin/sudo sysctl fs.inotify.max_queued_events=524288
  fs.inotify.max_queued_events = 524288
  /usr/bin/sudo sysctl -p
  vm.max_map_count = 262144
```

### Additional context
We did not experience this error last night. I'm not actually sure if this is caused by expo-github-action, some changes to GitHub Actions, or our repo. At the moment we run eas build locally but would like to be able to build via GitHub Actions.

**Comment by kennethlynne** [comment] 2022-01-06 12:45
Be ware we noticed the same problem, but for us it was in fact the install step that failed, not the patching. The logs could be improved.
What you initially see:
![image](https://user-images.githubusercontent.com/390817/148384879-16ff7432-63a2-4675-81f2-0066600542a4.png)

What you see when you expand the steps:
![image](https://user-images.githubusercontent.com/390817/148384847-44e749b4-9f98-4982-bd07-bedbf754193b.png)

Might not be your problem, but might be relevant for someone

**Comment by byCedric** [comment] 2022-01-06 20:52
If this is still an issue for you, can you try running with `packager: npm`? We didn't release a new version of EGH, and both Node/Yarn is running in the Github-managed part of the actions runner. (the part that you can't edit, [the runner context](https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#runsusing))

Either GitHub changed something in their Node12 setup, or Yarn is broken in some way at the moment. Will investigate further tomorrow morning CEST.

**Comment by javascripter** [comment] 2022-01-07 04:39
@byCedric I re-run the same workflow without any change a few more times today and they all ran successfully :) Not sure what's changed but It's working for us now :)

@kennethlynne True, when I expanded the failed workflow's `Installing eas-cli (0.43.0) with yarn` section, I indeed saw the same error, which seems to be the actual cause. 
```
  <--- JS stacktrace --->
  
  FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
   1: 0xb00d90 node::Abort() [node]
   2: 0xa1823b node::FatalError(char const*, char const*) [node]
   3: 0xcedbce v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
   4: 0xcedf47 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
   5: 0xea6105  [node]
```

**Comment by kennethlynne** [comment] 2022-01-07 10:08
Started working for us too today (thought it was some resolutions we added to package.json or upgrading node), but WTF 🥲. This is the second time it is the eas-cli step that fails with OOM tho in a couple of months, so something weird is going on that I do not understand

**Comment by kennethlynne** [comment] 2022-01-07 10:10
Btw: I had the issue locally when installing eas-cli in node 16.13.1, so it is not related to this repo!

**Comment by kennethlynne** [comment] 2022-01-07 10:16
To conclude: This means that the reported issue is a duplicate of https://github.com/expo/expo-github-action/issues/132 

To avoid more confusion the logs should probably be improved so it is easier to spot what actually failed

**Comment by byCedric** [comment] 2022-01-07 13:58
@kennethlynne can you share these dependency resolutions? I tried to reproduce the issue locally with the same Node and yarn versions, but on both Windows and macOS I couldn't reproduce it.

**Comment by kennethlynne** [comment] 2022-01-07 16:12
The only change in our codebase between the working and non-working commit was this, and I'm like wtf 😅 
```
+  "resolutions": {
+   "@apollo/client": "3.4.16"
+  },
```

**Comment by byCedric** [comment] 2022-01-16 17:30
I could not find the underlying cause, so for now I would consider this "an unexpected issue caused by yarn". I'll close this issue for now.

That being said, we now have a [simple e2e testing workflow that runs this action every day at 15:00](https://github.com/expo/expo-github-action/commit/fd33d597d339279a12768e1b3c99e051324dc8ba). If something similar like this goes down again, we should have at least more visibility on this. But for now, I'm not sure what the cause of the issue was.

Sorry for this, if you think otherwise, feel free to mention me 😄

**Closed by byCedric** 2022-01-16 17:30 UTC

**Comment by kennethlynne** [comment] 2022-01-17 12:50
No I agree, I have no more info to add. Will report back on this issue if it happens again. Thanks for looking into it 🙌
